### ISSUE TITLE
USER STORY: A customer signs up and/or logs in to the website

### ISSUE THREAD

**Issue by ssmerd** [ssmerd/epicurean#2]
As a **customer** I can **sign up and or/log in** so that **she can reserve a table**.

Acceptance criteria:

A user see a basic restaurant website with a link to sign up and or log in
A user can sign up and or log/in to the website.
A user's information is stored in a database model.
A user can login to the website and  make the reservation section

# Tasks

- [x] Create a signup page to store customer details
- [x] Create a login page
- [x] Let the logged in user to see the booking section
- [x] Test the new functionality
