### ISSUE TITLE
USER STORY: Book a table

### ISSUE THREAD

**Issue by ssmerd** [ssmerd/epicurean#3]
As a **customer** I can **fill in and post reservation details** so that **she can reserve a table**.

Acceptance criteria:

A user can fill in reservation information on the website
A user can reserve one or multiple tables if the number of clients don't fit into one table
A user can reserve a table for one hour

# Tasks
- [x] Build a reservation form
- [x] Build a reservation algorithm
- [x] Test the reservation algorithm
- [x]  Test the new functionality
